version: '2'
services:
    zookeeper:
        image: zookeeper:3.6.1
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
            ZOO_4LW_COMMANDS_WHITELIST: srvr,dump

    kafka:
        image: kafka-docker:2.13-2.6.0
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.1.20
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
            - zookeeper
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
